### ISSUE TITLE
怎么实现多轮对话呢

### ISSUE THREAD

**Issue by lzxlin** [TrustedLLM/TryMoreGPT#1]
您好，看例子TrymoreGPT可以支持多轮对话，请教下这个多轮对话是怎么实现的呀

**Comment by Hi-archers** [comment]
多轮对话的能力主要来自使用的shareGPT数据集，该数据集里面是人类和chatGPT聊天的内容。在实现的时候会以“人类：问题。助理：回答。人类：问题。助理：回答。”的格式迭代。

**Comment by lzxlin** [comment]
> 多轮对话的能力主要来自使用的shareGPT数据集，该数据集里面是人类和chatGPT聊天的内容。在实现的时候会以“人类：问题。助理：回答。人类：问题。助理：回答。”的格式迭代。

那意思是不是每个样本的输入就是多轮对话的内容呢，另外问下会不会开源训练的代码呀

**Comment by Hi-archers** [comment]
不是所有样本输入都是多轮对话，只有第一部分Share [GPT是多轮对话这部分数据大概有10w条，代码用的Vicuna([FastChat](https://github.com/lm-sys/FastChat))的训练代码，只是在他们的基础上针对中英双语对System] Prompt做了一定的修改，会在近期整理一份训练代码，推理代码，和WebUI代码。

**Comment by lzxlin** [comment]
> 不是所有样本输入都是多轮对话，只有第一部分Share [GPT是多轮对话这部分数据大概有10w条，代码用的Vicuna([FastChat](https://github.com/lm-sys/FastChat))的训练代码，只是在他们的基础上针对中英双语对System] Prompt做了一定的修改，会在近期整理一份训练代码，推理代码，和WebUI代码。

好的感谢
